export const allAnalysisKeys = {
  PastAnalysis: [
    "description",
    "interpretations",
    "behavior",
    "actualResult",
    "desiredResult",
    "comparison",
    "revision",
    "actionInterpretation",
    "behaviorChange",
    "implementation",
    "transfer",
  ],
  InnerSituationAnalysis: [
    "description",
    "interpretations",
    "behavior",
    "actualResult",
    "desiredResult",
    "comparison",
    "revision",
    "actionInterpretation",
    "behaviorChange",
    "implementation",
    "transfer",
  ],
  FutureAnalysis: [
    "description",
    "desiredResult",
    "behavior",
    "interpretations",
    "rolePlay",
    "implementation",
    "transfer",
  ],
};
